name: Validate Pull Request and auto-fix some issues

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  Validate:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install tools
        run: |
          pip install pre-commit

      # Run pre-commit --all-files
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        # Even if pre-commit gave an error, which it does always when it makes changes which we're trying to commit here
        if: always()
